Add optimizations for ZBB extension
MIPS/llvm pull request #5
Opened 2023-02-07 12:57 UTC by djtodoro

2023-04-28 12:43 UTC, draganmladjenovic commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +static SDValue foldSelectofCTTZ(SDNode *N, SelectionDAG &DAG) {
Is this a bit lax? What exact pattern do we wish to fold here

2023-05-05 10:43 UTC, djtodoro commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +static SDValue foldSelectofCTTZ(SDNode *N, SelectionDAG &DAG) {
Well. It needs more checks for sure. Thanks.

2023-05-05 11:04 UTC, draganmladjenovic requested changes

2023-05-05 11:04 UTC, draganmladjenovic commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +  if (FalseV != CTTZ)
Always false given the line 7586.

2023-05-05 11:04 UTC, draganmladjenovic commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +  //  The `true` branch should be constant `0`, `31` or `63`.
Shouldn't the constant be only 0? I fail to see how this optimization would be valid if we wish to produce 31, 63, or -1.

2023-05-05 11:10 UTC, djtodoro commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +  if (FalseV != CTTZ)
Not sure I follow.

2023-05-05 11:14 UTC, djtodoro commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +  if (FalseV != CTTZ)
Ah, yes.

2023-05-05 12:38 UTC, djtodoro commented on llvm/lib/Target/RISCV/RISCVISelLowering.cpp
> +  //  The `true` branch should be constant `0`, `31` or `63`.
Hmm, I agree. Let's avoid it for now. Looks like some tests were handwritten. I guess that the motivation behind was "whatever we chose (via `select`) in the case of ```0```, let's consider as a valid result". I think the motivation behind was taken from GCC (which does not imply to be correct).

2023-05-05 12:49 UTC, draganmladjenovic approved these changes

2023-05-05 15:45 UTC, merged